-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 10:19:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exo_sql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exo_sql` ;

-- -----------------------------------------------------
-- Schema exo_sql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exo_sql` ;
USE `exo_sql` ;

-- -----------------------------------------------------
-- Table `exo_sql`.`condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo_sql`.`condition` (
  `condition_id` INT NOT NULL AUTO_INCREMENT,
  `condition` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`condition_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_sql`.`fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo_sql`.`fact` (
  `article_id` INT NOT NULL AUTO_INCREMENT,
  `libellé` VARCHAR(45) NOT NULL,
  `prix` DECIMAL(6,2) NOT NULL,
  `condition_id` INT NOT NULL,
  `famille_id` INT NOT NULL,
  PRIMARY KEY (`article_id`, `condition_id`, `famille_id`),
  INDEX `fk_fact_condition_idx` (`condition_id` ASC) VISIBLE,
  INDEX `fk_fact_famille1_idx` (`famille_id` ASC) VISIBLE,
  CONSTRAINT `fk_fact_condition`
    FOREIGN KEY (`condition_id`)
    REFERENCES `exo_sql`.`condition` (`condition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_famille1`
    FOREIGN KEY (`famille_id`)
    REFERENCES `exo_sql`.`famille` (`famille_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_sql`.`famille`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo_sql`.`famille` (
  `famille_id` INT NOT NULL AUTO_INCREMENT,
  `famille` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`famille_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
